### ISSUE TITLE
Not all figures being generated

### ISSUE THREAD

**Issue by ericchen-udel** [VlachosGroup/AIMSim#170]
When checking Show Experimental Outliers, neither Similarity PDF nor Similarity Heatmap are generated
When checking Similarity Plot, none of the three mentioned before are generated. 

Used the following input, and used C=O as Target Molecule
[smiles.txt](https://github.com/VlachosGroup/molSim/files/7947688/smiles.txt)

**Comment by JacksonBurns** [comment]
Updates on this issue (this is a bit of a doozy):
 - all of the plots work individually, there are just some cases where combinations cause issues
 - target molecule similarity map does not show any other plots (database similarity plot, property similarity plot, and outlier check)
 - property similarity plot prevents database similarity plot from showing, but not outlier check

First and foremost - fix the target molecule similarity plot, which is hiding all others. Then look at property similarity plot, which only seems to negatively interact with the database similarity plot.

I have attached an updated smiles database file, with some added properties for full testing. I will check if this is just an issue with the GUI or the task manager.
[smiles.txt](https://github.com/VlachosGroup/AIMSim/files/9005670/smiles.txt)
