### ISSUE TITLE
Many dependency conflicts make installation impossible

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/AIMSim#247]
The very restricted dependency version requirements are making installation more and more difficult. Consider using >= version# for dependencies vs == version# or, at the very least consider limited use of == only when no other option will work.

scipy==1.5.4
matplotlib==3.3.4
seaborn==0.11.1
tabulate==0.8.9
numpy==1.21.0
multiprocess==0.70.12.2
scikit_learn_extra==0.2.0
pandas==1.1.5
mordred==1.2.0
PyYAML==5.4.1
scikit_learn==0.24.2
networkx==2.5
rdkit
psutil
padelpy
plotly
customtkinter<5.0.0
tkinter-tooltip

**Comment by JacksonBurns** [comment]
Thanks for bringing this up! When we initially made the requirements file, we only thought of the use case of users in a bare virtual environment and not those with an existing workflow trying to implement AIMSim.

Pull Request #241 will deal with dependency resolving using the methods you have described.

**Comment by JacksonBurns** [comment]
@wittregr I have just pushed AIMSim v2 to PyPI -- we have significantly reduced the dependency stiffness and validated the install on all platforms and Python version 3.7 to 3.11. It should be far easier to install now!
