### ISSUE TITLE
name ’warn‘ is not defined

### ISSUE THREAD

**Issue by lililololililolo** [VlachosGroup/AIMSim#264]
![1527b1245e01d9fb44d070188cb91fe](https://github.com/VlachosGroup/AIMSim/assets/125748286/1d666edf-84fc-402b-9766-b82eec923863)
what is ”name ’warn‘ is not defined“?

**Comment by JacksonBurns** [comment]
Hi @lililololililolo thanks for using AIMSim! This 'unexpected error' has been raised from a part of the code that we don't expect to break. Could you provide the input file and the GUI settings that you were using? That way I can reproduce the error locally to try and fix it.

**Comment by JacksonBurns** [comment]
Hello again @lililololililolo I have successfully found and resolved the issue! We were missing an important statement that would warn users that large datasets may take a long time to run. The 2.1.3 release will resolve this problem.
