### ISSUE TITLE
Containerize application

### ISSUE THREAD

**Issue by himaghna** [VlachosGroup/AIMSim#95]

**Comment by JacksonBurns** [comment]
I took a shot at this just out of curiosity, and you can try for yourself [on this branch](https://github.com/VlachosGroup/AIMSim/tree/docker-dev) (either build this, or [run this container](https://hub.docker.com/repository/docker/isthisinuse/aimsim)). I don't think this is really going to work - tkinter requires a virtual display to run, which in turn requires setting up an xserver and even then it is only ~10% functional. The Docker container is inherently separate from the OS, so getting new molecule database files in is a nightmare, and the plots don't seem to work in general.

Seems best to just stick with `pip install aimsim` as the only game in town.
